version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    - run: echo $CIRCLE_WORKFLOW_ID


jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - print_pipeline_id
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - welcome/run
      - save_hello_world_output