version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    # docker:
    #   - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "Hello world" > output.txt
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - target/output.txt

  print_output_file:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat target/output.txt
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:  [print_hello]