version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_world:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: echo "world"

  print_hello:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello"


workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:  [print_hello]
      