version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID


jobs:
  print_pipeline_id:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - print_pipeline_id

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file cloudformTemp.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["d816dcfdbda2fb018f15dd5520dccd7e"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible

      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

workflows:
  welcome:
    jobs:
      - welcome/run
      - print_pipeline_id
      #- create_infrastructure
      - configure_infrastructure